//camera_ioctl.h

#define CAMERA_IOCTL_MAGIC 'p'
#define CAMERA_IOCTL_GET 				_IOR(CAMERA_IOCTL_MAGIC, 0, int)
#define CAMERA_IOCTL_SET 				_IOWR(CAMERA_IOCTL_MAGIC, 1, int)
#define CAMERA_IOCTL_STREAMON 		_IOWR(CAMERA_IOCTL_MAGIC, 2, int)
#define CAMERA_IOCTL_STREAMOFF 		_IOWR(CAMERA_IOCTL_MAGIC, 3, int)
#define CAMERA_IOCTL_GRAB 				_IOWR(CAMERA_IOCTL_MAGIC, 4, int)
#define CAMERA_IOCTL_PANTILT 			_IOWR(CAMERA_IOCTL_MAGIC, 5, int)
#define CAMERA_IOCTL_PANTILT_RESET 	_IOWR(CAMERA_IOCTL_MAGIC, 6, int)

#define CAMERA_IOCTL_MAXNR 7
